// Progress charts and weekly volume.
function allExercisesList(){ const set=new Set(); state.routines.forEach(r=>r.exercises.forEach(e=>set.add(e))); state.sessions.forEach(s=>s.exercises.forEach(e=>set.add(e.name))); return Array.from(set); }
function renderProgreso(){
  const all=allExercisesList(); if(!all.length)return `<div class="empty">Registrá una sesión para ver tu progreso.</div>`;
  if(!state.prog.exercise||!all.includes(state.prog.exercise))state.prog.exercise=all[0]; const exercise=state.prog.exercise; const points=[];
  state.sessions.slice().sort((a,b)=>a.date.localeCompare(b.date)).forEach(s=>{const ex=s.exercises.find(e=>e.name===exercise);if(!ex||!ex.sets.length)return;points.push({date:s.date.slice(5),maxWeight:Math.max(...ex.sets.map(st=>st.weight)),volume:ex.sets.reduce((sum,st)=>sum+st.weight*st.reps,0)});});
  let html=`<select onchange="setProgExercise(this.value)" style="margin-bottom:14px;font-weight:600;">${all.map(ex=>`<option value="${esc(ex)}" ${ex===exercise?'selected':''}>${esc(ex)}</option>`).join("")}</select>`;
  if(!points.length)return html+`<div class="empty">Sin datos todavía para ${esc(exercise)}.</div>`;
  const last=points[points.length-1],first=points[0]; html+=chartCard("PESO MÁXIMO POR SESIÓN",last.maxWeight+" kg",(last.maxWeight-first.maxWeight).toFixed(1),points,"maxWeight","#B5502F"); html+=chartCard("VOLUMEN TOTAL POR SESIÓN",last.volume+" kg",(last.volume-first.volume).toFixed(0),points,"volume","#1A1918"); const weekly=weeklyVolumePoints(); if(weekly.length)html+=chartCard("VOLUMEN TOTAL POR SEMANA",weekly[weekly.length-1].volume+" kg",(weekly[weekly.length-1].volume-weekly[0].volume).toFixed(0),weekly,"volume","#5B7A4A"); return html;
}
function weeklyVolumePoints(){const totals={};state.sessions.forEach(session=>{const date=new Date(`${session.date}T12:00:00`),monday=new Date(date);monday.setDate(date.getDate()-mondayIndex(date));const key=fmtDateKey(monday);totals[key]=(totals[key]||0)+session.exercises.reduce((total,ex)=>total+ex.sets.reduce((sum,set)=>sum+set.weight*set.reps,0),0);});return Object.entries(totals).sort(([a],[b])=>a.localeCompare(b)).map(([date,volume])=>({date:date.slice(5),volume}));}
function setProgExercise(v){state.prog.exercise=v;render();}
function chartCard(title,value,delta,points,key,color){const w=300,h=120,pad=8,vals=points.map(p=>p[key]),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,stepX=points.length>1?(w-pad*2)/(points.length-1):0,coords=points.map((p,i)=>[pad+i*stepX,h-pad-((p[key]-min)/range)*(h-pad*2)]),path=coords.map((c,i)=>(i===0?"M":"L")+c[0].toFixed(1)+","+c[1].toFixed(1)).join(" "),dots=coords.map(c=>`<circle cx="${c[0].toFixed(1)}" cy="${c[1].toFixed(1)}" r="3" fill="${color}"/>`).join(""),deltaNum=parseFloat(delta);return `<div class="card"><div class="tag">${title}</div><div style="display:flex;align-items:baseline;gap:8px;margin:6px 0 10px;"><span style="font-size:20px;font-weight:700;">${value}</span><span style="font-size:12px;font-weight:600;color:${deltaNum>=0?'#5B7A4A':'#B5502F'}">(${deltaNum>=0?'+':''}${delta})</span></div><svg width="100%" height="${h}" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" style="overflow:visible;"><path d="${path}" fill="none" stroke="${color}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>${dots}</svg></div>`;}
