// Routine management.
function renderRutinas(){
  let html = `<div class="routine-intro"><strong>Organizá tus entrenamientos</strong><span>Creá rutinas y agregá los ejercicios que querés seguir.</span></div>`;
  html += state.routines.map(r => `<section class="routine-editor"><div class="routine-editor-header"><div class="routine-title-field"><label for="routine-name-${r.id}">Nombre de la rutina</label><input id="routine-name-${r.id}" value="${esc(r.name)}" aria-label="Nombre de la rutina ${esc(r.name)}"></div><button class="icon-btn routine-delete" onclick="removeRoutine('${r.id}')" aria-label="Eliminar rutina">${ICONS.trash}</button></div><div class="routine-exercises-label">EJERCICIOS <span>${r.exercises.length}</span></div><div class="routine-exercises">${r.exercises.length ? r.exercises.map((ex,idx)=>`<div class="routine-exercise"><span class="routine-exercise-number">${idx+1}</span><span>${esc(ex)}</span><button class="icon-btn" onclick="removeExercise('${r.id}',${idx})" aria-label="Quitar ${esc(ex)}">${ICONS.x}</button></div>`).join("") : `<div class="routine-empty">Todavía no hay ejercicios.</div>`}</div><div class="routine-add-exercise"><input id="exinput-${r.id}" placeholder="Ej. Press banca" aria-label="Nuevo ejercicio para ${esc(r.name)}"><button class="btn btn-small" onclick="addExercise('${r.id}')">${ICONS.plus} Agregar</button></div><button class="btn btn-save-routine" onclick="saveRoutineName('${r.id}')">Guardar cambios</button></section>`).join("");
  html += `<section class="new-routine"><div><strong>Nueva rutina</strong><span>Empezá una rutina desde cero.</span></div><div class="new-routine-form"><input id="newRoutineName" placeholder="Ej. Tren superior" aria-label="Nombre de nueva rutina"><button class="btn btn-primary btn-small" onclick="addRoutine()">${ICONS.plus} Crear rutina</button></div></section>`;
  return html;
}
function addRoutine(){ const input=document.getElementById("newRoutineName"); const name=input.value.trim(); if(!name)return; const routine={id:uid(),name,exercises:[]}; state.routines.push(routine); saveData({type:"upsert",table:"routines",record:routine}); render(); }
function removeRoutine(id){ state.routines=state.routines.filter(r=>r.id!==id); removeCloudRecord("routines",id).then(render); }
function saveRoutineName(routineId){ const routine=state.routines.find(x=>x.id===routineId); const input=document.getElementById("routine-name-"+routineId); if(!routine||!input)return; const name=input.value.trim(); if(!name){ input.value=routine.name; return; } routine.name=name; saveData({type:"upsert",table:"routines",record:routine}); render(); }
function addExercise(routineId){ const input=document.getElementById("exinput-"+routineId); const name=input.value.trim(); if(!name)return; const routine=state.routines.find(x=>x.id===routineId); routine.exercises.push(name); saveData({type:"upsert",table:"routines",record:routine}); render(); }
function removeExercise(routineId,idx){ const routine=state.routines.find(x=>x.id===routineId); routine.exercises.splice(idx,1); saveData({type:"upsert",table:"routines",record:routine}); render(); }
