// Routine management.
function renderRutinas(){
  let html = state.routines.map(r => `<div class="card"><div class="row" style="justify-content:space-between;margin-bottom:8px;"><div style="font-weight:600;">${esc(r.name)}</div><button class="icon-btn" onclick="removeRoutine('${r.id}')">${ICONS.trash}</button></div>${r.exercises.map((ex,idx)=>`<div class="row" style="justify-content:space-between;font-size:14px;color:#4A4844;margin-bottom:4px;"><span>${esc(ex)}</span><button class="icon-btn" style="color:#8B8680" onclick="removeExercise('${r.id}',${idx})">${ICONS.x}</button></div>`).join("")}<div class="row" style="margin-top:8px;"><input id="exinput-${r.id}" placeholder="Nuevo ejercicio" style="flex:1"/><button class="icon-btn" style="font-weight:600;font-size:13px;" onclick="addExercise('${r.id}')">Agregar</button></div></div>`).join("");
  return html + `<div class="card row"><input id="newRoutineName" placeholder="Nueva rutina" style="flex:1"/><button class="btn" style="background:#B5502F;color:#F3EFE6;flex-shrink:0;" onclick="addRoutine()">${ICONS.plus}</button></div>`;
}
function addRoutine(){ const input=document.getElementById("newRoutineName"); const name=input.value.trim(); if(!name)return; const routine={id:uid(),name,exercises:[]}; state.routines.push(routine); saveData({type:"upsert",table:"routines",record:routine}); render(); }
function removeRoutine(id){ state.routines=state.routines.filter(r=>r.id!==id); removeCloudRecord("routines",id).then(render); }
function addExercise(routineId){ const input=document.getElementById("exinput-"+routineId); const name=input.value.trim(); if(!name)return; const routine=state.routines.find(x=>x.id===routineId); routine.exercises.push(name); saveData({type:"upsert",table:"routines",record:routine}); render(); }
function removeExercise(routineId,idx){ const routine=state.routines.find(x=>x.id===routineId); routine.exercises.splice(idx,1); saveData({type:"upsert",table:"routines",record:routine}); render(); }
